services:
    postgres:
        container_name: postgres
        image: postgres:alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=none
            - POSTGRES_DB=catering
        ports:
            - "5000:5432"
        healthcheck:
            test: pg_isready -U postgres
            interval: 10s
            timeout: 5s
            retries: 5

    catering-backend:
        container_name: catering-backend
        hostname: catering-backend
        image: catering-backend:prod
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=none
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/catering
        ports:
            - "8080:8080"
