services:
    postgres:
        env_file:
            -   .env
        container_name: postgres
        image: postgres:alpine
        ports:
            - "5000:5432"
        healthcheck:
            test: pg_isready -U postgres
            interval: 10s
            timeout: 5s
            retries: 5

    catering-backend:
        env_file:
            -   .env
        container_name: catering-backend
        hostname: catering-backend
        image: catering-backend:prod
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - "8080:8080"
