server:
    port: 8080

    http2:
        enabled: true

    servlet:
        context-path: /

    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 512

spring:
    application:
        name: backend

openapi:
    service:
        title: Catering Backend
        version: 1.0.0
        url: http://localhost:8080
